server:
  port: 8080
logging:
  level:
    org:
      springframework:
        web: DEBUG

spring:
  datasource:
    url: jdbc:mysql://10.111.111.50/scada_datastream
    username: sammy
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: update
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    show-sql: true
#    properties:
#     hibernate:
#       hibernate.format_sql: true
#       ddl-auto: update


app:
  jwt-secret: 77397A244326462948404D635166546A576E5A7234753778214125442A472D4B
  jwt-expiration-milliseconds: 120000